# Generated by Django 5.2.7 on 2025-10-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
