# Generated by Django 5.2.7 on 2025-10-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_first_name_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
